=begin
#ChannelShipper & Royal Mail Public API

#Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for ClickAndDrop::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @api_instance = ClickAndDrop::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@api_instance).to be_instance_of(ClickAndDrop::OrdersApi)
    end
  end

  # unit tests for create_orders_async
  # Create orders
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [CreateOrdersResponse]
  describe 'create_orders_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_orders_async
  # Delete orders
  # &lt;b&gt;Reserved for ChannelShipper customers only - please visit  &lt;a href&#x3D;\&quot;https://channelshipper.com/\&quot; target&#x3D;\&quot;_self\&quot;&gt;ChannelShipper.com&lt;/a&gt; for more information&lt;/b&gt;  Please be aware labels generated on orders which are deleted are no longer valid and must be destroyed.  Cancelled label information is automatically shared with Royal Mail Revenue Protection, and should  a cancelled label be identified on an item in the Royal Mail Network, you will be charged on your account  and an additional handling fee applied. 
  # @param order_identifiers One or several Order Identifiers or Order References separated by semicolon. Order Identifiers are integer numbers. Order References are strings - each must be percent-encoded and surrounded by double quotation marks.
  # @param [Hash] opts the optional parameters
  # @return [DeleteOrdersResource]
  describe 'delete_orders_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_orders_async
  # Retrieve orders
  # @param order_identifiers One or several Order Identifiers or Order References separated by semicolon. Order Identifiers are integer numbers. Order References are strings - each must be percent-encoded and surrounded by double quotation marks.
  # @param [Hash] opts the optional parameters
  # @return [Array<GetOrderInfoResource>]
  describe 'get_orders_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_orders_with_details_async
  # Retrieve orders details
  # &lt;b&gt;Reserved for ChannelShipper customers only - please visit &lt;a href&#x3D;\&quot;https://channelshipper.com/\&quot; target&#x3D;\&quot;_self\&quot;&gt;ChannelShipper.com&lt;/a&gt; for more information&lt;/b&gt;
  # @param order_identifiers One or several Order Identifiers or Order References separated by semicolon. Order Identifiers are integer numbers. Order References are strings - each must be percent-encoded and surrounded by double quotation marks.
  # @param [Hash] opts the optional parameters
  # @return [Array<GetOrderDetailsResource>]
  describe 'get_orders_with_details_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_orders_status_async
  # Set order status
  # @param request At least one of &#39;orderIdentifier&#39; and &#39;orderReference&#39; is required. Providing both is disallowed to avoid ambiguity.  When the status is set to &#39;despatchedByOtherCourier&#39;, if the optional parameter &#39;trackingNumber&#39; is provided  then the parameters &#39;despatchDate&#39;, &#39;shippingCarrier&#39; and &#39;shippingService&#39; are also required. 
  # @param [Hash] opts the optional parameters
  # @return [UpdateOrderStatusResponse]
  describe 'update_orders_status_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
