=begin
#ChannelShipper & Royal Mail Public API

#Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ClickAndDrop::ShipmentPackageRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ClickAndDrop::ShipmentPackageRequest do
  let(:instance) { ClickAndDrop::ShipmentPackageRequest.new }

  describe 'test an instance of ShipmentPackageRequest' do
    it 'should create an instance of ShipmentPackageRequest' do
      expect(instance).to be_instance_of(ClickAndDrop::ShipmentPackageRequest)
    end
  end
  describe 'test attribute "weight_in_grams"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "package_format_identifier"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["undefined", "letter", "largeLetter", "smallParcel", "mediumParcel", "parcel", "documents", "custom"])
      # validator.allowable_values.each do |value|
      #   expect { instance.package_format_identifier = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "custom_package_format_identifier"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "dimensions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contents"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
