=begin
#ChannelShipper & Royal Mail Public API

#Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

# Common files
require 'click_and_drop/api_client'
require 'click_and_drop/api_error'
require 'click_and_drop/version'
require 'click_and_drop/configuration'

# Models
require 'click_and_drop/models/address_request'
require 'click_and_drop/models/billing_details_request'
require 'click_and_drop/models/create_order_error_response'
require 'click_and_drop/models/create_order_label_error_response'
require 'click_and_drop/models/create_order_request'
require 'click_and_drop/models/create_order_response'
require 'click_and_drop/models/create_orders_request'
require 'click_and_drop/models/create_orders_response'
require 'click_and_drop/models/delete_orders_resource'
require 'click_and_drop/models/deleted_order_info'
require 'click_and_drop/models/dimensions_request'
require 'click_and_drop/models/error_response'
require 'click_and_drop/models/failed_order_response'
require 'click_and_drop/models/get_order_details_resource'
require 'click_and_drop/models/get_order_info_resource'
require 'click_and_drop/models/get_order_line_result'
require 'click_and_drop/models/get_postal_details_result'
require 'click_and_drop/models/get_shipping_details_result'
require 'click_and_drop/models/get_tag_details_result'
require 'click_and_drop/models/get_version_resource'
require 'click_and_drop/models/label_generation_request'
require 'click_and_drop/models/order_error_info'
require 'click_and_drop/models/order_error_response'
require 'click_and_drop/models/order_field_response'
require 'click_and_drop/models/order_update_error'
require 'click_and_drop/models/postage_details_request'
require 'click_and_drop/models/product_item_request'
require 'click_and_drop/models/recipient_details_request'
require 'click_and_drop/models/sender_details_request'
require 'click_and_drop/models/shipment_package_request'
require 'click_and_drop/models/tag_request'
require 'click_and_drop/models/update_order_status_request'
require 'click_and_drop/models/update_order_status_response'
require 'click_and_drop/models/update_orders_status_request'
require 'click_and_drop/models/updated_order_info'

# APIs
require 'click_and_drop/api/labels_api'
require 'click_and_drop/api/orders_api'
require 'click_and_drop/api/version_api'

module ClickAndDrop
  class << self
    # Customize default settings for the SDK using block.
    #   ClickAndDrop.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
